# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(480, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(63, 63, 63);")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-380, 0, 871, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("menu_pic.png"))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 90, 131, 36))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 18pt \"Times New Roman\";")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 81, 16))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 192, 141);\n"
"font: 12pt \"Times New Roman\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 210, 101, 31))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Times New Roman\";")
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(163, 520, 155, 29))
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 192, 141);\n"
"font: 14pt \"Times New Roman\";\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(3, 520, 155, 29))
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 192, 141);\n"
"font: 14pt \"Times New Roman\";\n"
"")
        self.pushButton.setIconSize(QtCore.QSize(16, 16))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(323, 520, 155, 29))
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 192, 141);\n"
"font: 14pt \"Times New Roman\";\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(335, 290, 110, 110))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(182, 166, 158);\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-radius: 30px;\n"
"border-color: rgb(129, 118, 109);\n"
"max-width: 100px;\n"
"max-height: 100px;\n"
"min-width: 100px;\n"
"min-height: 100px;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(35, 290, 110, 110))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(182, 166, 158);\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-radius: 30px;\n"
"border-color: rgb(129, 118, 109);\n"
"max-width: 100px;\n"
"max-height: 100px;\n"
"min-width: 100px;\n"
"min-height: 100px;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(185, 290, 110, 110))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(182, 166, 158);\n"
"border-style: solid;\n"
"border-width: 5px;\n"
"border-radius: 30px;\n"
"border-color: rgb(129, 118, 109);\n"
"max-width: 100px;\n"
"max-height: 100px;\n"
"min-width: 100px;\n"
"min-height: 100px;")
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "МоиДеньги"))
        self.label_3.setText(_translate("MainWindow", "0.00 ₽"))
        self.label_2.setText(_translate("MainWindow", "В кошельке"))
        self.label_2.resize(self.label_2.sizeHint())
        self.label_4.setText(_translate("MainWindow", "Баллы: 0"))
        self.pushButton_3.setText(_translate("MainWindow", "ПОПОЛНИТЬ"))
        self.pushButton.setText(_translate("MainWindow", "ВЫХОД"))
        self.pushButton_2.setText(_translate("MainWindow", "ПЕРЕВОД"))
        self.pushButton_4.setText(_translate("MainWindow", "Открыть\n"
"браузер"))
        self.pushButton_5.setText(_translate("MainWindow", "Купить\n"
"или\n"
"потратить\n"
"баллы"))
        self.pushButton_6.setText(_translate("MainWindow", "Виртуальная\n"
"карта"))