# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pay_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(620, 165)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(63, 63, 63);")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.cardData = QtWidgets.QLineEdit(self.centralwidget)
        self.cardData.setGeometry(QtCore.QRect(10, 40, 594, 20))
        self.cardData.setStyleSheet("color: rgb(118, 192, 141);")
        self.cardData.setObjectName("cardData")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.amountData = QtWidgets.QLineEdit(self.centralwidget)
        self.amountData.setGeometry(QtCore.QRect(10, 90, 594, 20))
        self.amountData.setStyleSheet("color: rgb(118, 192, 141);")
        self.amountData.setObjectName("amountData")
        self.payButton = QtWidgets.QPushButton(self.centralwidget)
        self.payButton.setGeometry(QtCore.QRect(210, 120, 161, 31))
        self.payButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(118, 192, 141);\n"
"font: 14pt \"Times New Roman\";\n"
"")
        self.payButton.setObjectName("payButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 120, 51, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Пополнение"))
        self.label.setText(_translate("MainWindow", "Введите номер карты:"))
        self.label.resize(self.label.sizeHint())
        self.label_2.setText(_translate("MainWindow", "Введите сумму пополнения в ₽:"))
        self.label_2.resize(self.label_2.sizeHint())
        self.payButton.setText(_translate("MainWindow", "ПОПОЛНИТЬ"))
        self.pushButton_2.setText(_translate("MainWindow", "<--\n"
"Назад"))
